# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformancecheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockervijeta.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_821387f20d7c460496a8a68438e960bc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_324de9d73e75443a876c9de9e85023a6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockervijeta.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_821387f20d7c460496a8a68438e960bc }}/studentperformance1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformancecheck'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b5944abd2211444493c10517485670ac }}
        images: 'testdockervijeta.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_821387f20d7c460496a8a68438e960bc }}/studentperformance1:${{ github.sha }}'